
import os

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA_DIR = os.path.join(PROJECT_ROOT, "data")
FILINGS_DIR = os.path.join(DATA_DIR, "filings")
VECTORS_DIR = os.path.join(DATA_DIR, "vectors")
DB_PATH = os.path.join(DATA_DIR, "las_store.db")
DATABASE_URL = os.environ.get("DATABASE_URL", f"sqlite:///{DB_PATH}")

# SEC / Filing settings
FILING_TYPES = ["10-K", "10-Q"]
MAX_FILINGS_PER_CIK = 5   # per filing type

# ---------------------------------------------------------------------------
# Universe toggle: set to "demo" for 50-ticker subset, "full" for all S&P 500.
# Switch this flag to control which tickers the pipeline and backtest use.
# ---------------------------------------------------------------------------
UNIVERSE_MODE = "demo"  # "demo" | "full"

# 50-ticker demo subset — balanced across all 11 GICS sectors.
# Includes all original Dow 30 names with data + key S&P 500 additions.
DEMO_TICKERS = {
    # Technology (6)
    "AAPL", "MSFT", "NVDA", "GOOGL", "META", "CRM", "CSCO", "INTC",
    # Financial Services (7)
    "JPM", "GS", "V", "MA", "BLK", "AXP", "SCHW",
    # Healthcare (6)
    "UNH", "JNJ", "LLY", "PFE", "AMGN", "MRK",
    # Consumer Cyclical (5)
    "AMZN", "TSLA", "HD", "NKE", "MCD",
    # Consumer Defensive (4)
    "PG", "KO", "WMT", "COST",
    # Industrials (5)
    "BA", "CAT", "HON", "UPS", "DE",
    # Communication Services (3)
    "DIS", "NFLX", "TMUS",
    # Energy (3)
    "CVX", "XOM", "COP",
    # Basic Materials (3)
    "DOW", "LIN", "FCX",
    # Utilities (3)
    "NEE", "DUK", "SO",
    # Real Estate (3)
    "AMT", "PLD", "EQIX",
}

# S&P 500 — Keys are CIK integers, values are ticker strings.
CIK_TO_TICKER = {
    1090872: "A",
    320193: "AAPL",
    1551152: "ABBV",
    1559720: "ABNB",
    1800: "ABT",
    947484: "ACGL",
    1467373: "ACN",
    796343: "ADBE",
    6281: "ADI",
    7084: "ADM",
    8670: "ADP",
    769397: "ADSK",
    1002910: "AEE",
    4904: "AEP",
    874761: "AES",
    4977: "AFL",
    5272: "AIG",
    1267238: "AIZ",
    354190: "AJG",
    1086222: "AKAM",
    915913: "ALB",
    1097149: "ALGN",
    899051: "ALL",
    1579241: "ALLE",
    6951: "AMAT",
    1748790: "AMCR",
    2488: "AMD",
    1037868: "AME",
    318154: "AMGN",
    820027: "AMP",
    1053507: "AMT",
    1018724: "AMZN",
    1596532: "ANET",
    315293: "AON",
    91142: "AOS",
    1841666: "APA",
    2969: "APD",
    820313: "APH",
    1858681: "APO",
    1751008: "APP",
    1521332: "APTV",
    1035443: "ARE",
    1176948: "ARES",
    731802: "ATO",
    915912: "AVB",
    1730168: "AVGO",
    8818: "AVY",
    1410636: "AWK",
    1069183: "AXON",
    4962: "AXP",
    866787: "AZO",
    12927: "BA",
    70858: "BAC",
    9389: "BALL",
    10456: "BAX",
    764478: "BBY",
    10795: "BDX",
    38777: "BEN",
    14693: "BF.B",
    1996862: "BG",
    875045: "BIIB",
    1390777: "BK",
    1075531: "BKNG",
    1701605: "BKR",
    1316835: "BLDR",
    2012383: "BLK",
    14272: "BMY",
    1383312: "BR",
    1067983: "BRK.B",
    79282: "BRO",
    885725: "BSX",
    1393818: "BX",
    1037540: "BXP",
    831001: "C",
    23217: "CAG",
    721371: "CAH",
    1783180: "CARR",
    726958: "CASY",
    18230: "CAT",
    896159: "CB",
    1374310: "CBOE",
    1138118: "CBRE",
    1051470: "CCI",
    815097: "CCL",
    813672: "CDNS",
    1402057: "CDW",
    1868275: "CEG",
    1324404: "CF",
    759944: "CFG",
    313927: "CHD",
    1043277: "CHRW",
    1091667: "CHTR",
    1739940: "CI",
    936395: "CIEN",
    20286: "CINF",
    21665: "CL",
    21076: "CLX",
    1166691: "CMCSA",
    1156375: "CME",
    1058090: "CMG",
    26172: "CMI",
    811156: "CMS",
    1071739: "CNC",
    1130310: "CNP",
    927628: "COF",
    820318: "COHR",
    1679788: "COIN",
    711404: "COO",
    1163165: "COP",
    1140859: "COR",
    909832: "COST",
    1175454: "CPAY",
    16732: "CPB",
    900075: "CPRT",
    906345: "CPT",
    849395: "CRH",
    1100682: "CRL",
    1108524: "CRM",
    1535527: "CRWD",
    858877: "CSCO",
    1057352: "CSGP",
    277948: "CSX",
    723254: "CTAS",
    858470: "CTRA",
    1058290: "CTSH",
    1755672: "CTVA",
    1690820: "CVNA",
    64803: "CVS",
    93410: "CVX",
    715957: "D",
    27904: "DAL",
    1792789: "DASH",
    1666700: "DD",
    1561550: "DDOG",
    315189: "DE",
    910521: "DECK",
    1571996: "DELL",
    29534: "DG",
    1022079: "DGX",
    882184: "DHI",
    313616: "DHR",
    1744489: "DIS",
    1297996: "DLR",
    935703: "DLTR",
    765880: "DOC",
    29905: "DOV",
    1751788: "DOW",
    1286681: "DPZ",
    940944: "DRI",
    936340: "DTE",
    1326160: "DUK",
    927066: "DVA",
    1090012: "DVN",
    1093557: "DXCM",
    712515: "EA",
    1065088: "EBAY",
    31462: "ECL",
    1047862: "ED",
    33185: "EFX",
    1095073: "EG",
    827052: "EIX",
    1001250: "EL",
    1156039: "ELV",
    105634: "EME",
    32604: "EMR",
    821189: "EOG",
    1352010: "EPAM",
    1101239: "EQIX",
    906107: "EQR",
    33213: "EQT",
    922621: "ERIE",
    72741: "ES",
    920522: "ESS",
    1551182: "ETN",
    65984: "ETR",
    1711269: "EVRG",
    1099800: "EW",
    1109357: "EXC",
    895126: "EXE",
    746515: "EXPD",
    1324424: "EXPE",
    1289490: "EXR",
    37996: "F",
    1539838: "FANG",
    815556: "FAST",
    831259: "FCX",
    1013237: "FDS",
    1048911: "FDX",
    1031296: "FE",
    1048695: "FFIV",
    814547: "FICO",
    1136893: "FIS",
    798354: "FISV",
    35527: "FITB",
    1035983: "FIX",
    1754301: "FOX",
    1754301: "FOXA",
    34903: "FRT",
    1274494: "FSLR",
    1262039: "FTNT",
    1659166: "FTV",
    40533: "GD",
    1609711: "GDDY",
    40545: "GE",
    1932393: "GEHC",
    849399: "GEN",
    1996810: "GEV",
    882095: "GILD",
    40704: "GIS",
    320335: "GL",
    24741: "GLW",
    1467858: "GM",
    1474735: "GNRC",
    1652044: "GOOG",
    1652044: "GOOGL",
    40987: "GPC",
    1123360: "GPN",
    1121788: "GRMN",
    886982: "GS",
    277135: "GWW",
    45012: "HAL",
    46080: "HAS",
    49196: "HBAN",
    860730: "HCA",
    354950: "HD",
    874766: "HIG",
    1501585: "HII",
    1585689: "HLT",
    773840: "HON",
    1783879: "HOOD",
    1645590: "HPE",
    47217: "HPQ",
    48465: "HRL",
    1000228: "HSIC",
    1070750: "HST",
    47111: "HSY",
    48898: "HUBB",
    49071: "HUM",
    4281: "HWM",
    1381197: "IBKR",
    51143: "IBM",
    1571949: "ICE",
    874716: "IDXX",
    832101: "IEX",
    51253: "IFF",
    879169: "INCY",
    50863: "INTC",
    896878: "INTU",
    1687229: "INVH",
    51434: "IP",
    1478242: "IQV",
    1699150: "IR",
    1020569: "IRM",
    1035267: "ISRG",
    749251: "IT",
    49826: "ITW",
    914208: "IVZ",
    52988: "J",
    728535: "JBHT",
    898293: "JBL",
    833444: "JCI",
    779152: "JKHY",
    200406: "JNJ",
    19617: "JPM",
    1418135: "KDP",
    91576: "KEY",
    1601046: "KEYS",
    1637459: "KHC",
    879101: "KIM",
    1404912: "KKR",
    319201: "KLAC",
    55785: "KMB",
    1506307: "KMI",
    21344: "KO",
    56873: "KR",
    1944048: "KVUE",
    60086: "L",
    1336920: "LDOS",
    920760: "LEN",
    920148: "LH",
    202058: "LHX",
    1069202: "LII",
    1707925: "LIN",
    1633978: "LITE",
    59478: "LLY",
    936468: "LMT",
    352541: "LNT",
    60667: "LOW",
    707549: "LRCX",
    1397187: "LULU",
    92380: "LUV",
    1300514: "LVS",
    1489393: "LYB",
    1335258: "LYV",
    1141391: "MA",
    912595: "MAA",
    1048286: "MAR",
    62996: "MAS",
    63908: "MCD",
    827054: "MCHP",
    927653: "MCK",
    1059556: "MCO",
    1103982: "MDLZ",
    1613103: "MDT",
    1099219: "MET",
    1326801: "META",
    789570: "MGM",
    63754: "MKC",
    916076: "MLM",
    66740: "MMM",
    865752: "MNST",
    764180: "MO",
    1285785: "MOS",
    1510295: "MPC",
    1280452: "MPWR",
    310158: "MRK",
    1682852: "MRNA",
    62709: "MRSH",
    895421: "MS",
    1408198: "MSCI",
    789019: "MSFT",
    68505: "MSI",
    36270: "MTB",
    1037646: "MTD",
    723125: "MU",
    1513761: "NCLH",
    1120193: "NDAQ",
    72331: "NDSN",
    753308: "NEE",
    1164727: "NEM",
    1065280: "NFLX",
    1111711: "NI",
    320187: "NKE",
    1133421: "NOC",
    1373715: "NOW",
    1013871: "NRG",
    702165: "NSC",
    1002047: "NTAP",
    73124: "NTRS",
    73309: "NUE",
    1045810: "NVDA",
    906163: "NVR",
    1564708: "NWS",
    1564708: "NWSA",
    1413447: "NXPI",
    726728: "O",
    878927: "ODFL",
    1039684: "OKE",
    29989: "OMC",
    1097864: "ON",
    1341439: "ORCL",
    898173: "ORLY",
    1781335: "OTIS",
    797468: "OXY",
    1327567: "PANW",
    723531: "PAYX",
    75362: "PCAR",
    1004980: "PCG",
    788784: "PEG",
    77476: "PEP",
    78003: "PFE",
    1126328: "PFG",
    80424: "PG",
    80661: "PGR",
    76334: "PH",
    822416: "PHM",
    75677: "PKG",
    1045609: "PLD",
    1321655: "PLTR",
    1413329: "PM",
    713676: "PNC",
    77360: "PNR",
    764622: "PNW",
    1145197: "PODD",
    945841: "POOL",
    79879: "PPG",
    922224: "PPL",
    1137774: "PRU",
    1393311: "PSA",
    2041610: "PSKY",
    1534701: "PSX",
    857005: "PTC",
    1050915: "PWR",
    1633917: "PYPL",
    2058873: "Q",
    804328: "QCOM",
    884887: "RCL",
    910606: "REG",
    872589: "REGN",
    1281761: "RF",
    720005: "RJF",
    1037038: "RL",
    943819: "RMD",
    1024478: "ROK",
    84839: "ROL",
    882835: "ROP",
    745732: "ROST",
    1060391: "RSG",
    101829: "RTX",
    31791: "RVTY",
    1415404: "SATS",
    1034054: "SBAC",
    829224: "SBUX",
    316709: "SCHW",
    89800: "SHW",
    91419: "SJM",
    87347: "SLB",
    1375365: "SMCI",
    91440: "SNA",
    2023554: "SNDK",
    883241: "SNPS",
    92122: "SO",
    1964738: "SOLV",
    1063761: "SPG",
    64040: "SPGI",
    1032208: "SRE",
    1757898: "STE",
    1022671: "STLD",
    93751: "STT",
    1137789: "STX",
    16918: "STZ",
    2005951: "SW",
    93556: "SWK",
    4127: "SWKS",
    1601712: "SYF",
    310764: "SYK",
    96021: "SYY",
    732717: "T",
    24545: "TAP",
    1260221: "TDG",
    1094285: "TDY",
    842023: "TECH",
    1385157: "TEL",
    97210: "TER",
    92230: "TFC",
    27419: "TGT",
    109198: "TJX",
    1973266: "TKO",
    97745: "TMO",
    1283699: "TMUS",
    1811074: "TPL",
    1116132: "TPR",
    1389170: "TRGP",
    864749: "TRMB",
    1113169: "TROW",
    86312: "TRV",
    916365: "TSCO",
    1318605: "TSLA",
    100493: "TSN",
    1466258: "TT",
    1671933: "TTD",
    946581: "TTWO",
    97476: "TXN",
    217346: "TXT",
    860731: "TYL",
    100517: "UAL",
    1543151: "UBER",
    74208: "UDR",
    352915: "UHS",
    1403568: "ULTA",
    731766: "UNH",
    100885: "UNP",
    1090727: "UPS",
    1067701: "URI",
    36104: "USB",
    1403161: "V",
    1705696: "VICI",
    1035002: "VLO",
    1967680: "VLTO",
    1396009: "VMC",
    1442145: "VRSK",
    1014473: "VRSN",
    1674101: "VRT",
    875320: "VRTX",
    1692819: "VST",
    740260: "VTR",
    1792044: "VTRS",
    732712: "VZ",
    943452: "WAB",
    1000697: "WAT",
    1437107: "WBD",
    1327811: "WDAY",
    106040: "WDC",
    783325: "WEC",
    766704: "WELL",
    72971: "WFC",
    823768: "WM",
    107263: "WMB",
    104169: "WMT",
    11544: "WRB",
    719955: "WSM",
    105770: "WST",
    1140536: "WTW",
    106535: "WY",
    1174922: "WYNN",
    72903: "XEL",
    34088: "XOM",
    1524472: "XYL",
    1512673: "XYZ",
    1041061: "YUM",
    1136869: "ZBH",
    877212: "ZBRA",
    1555280: "ZTS",
}

_CIK_TO_TICKER_FULL = CIK_TO_TICKER

# Apply universe filter — when UNIVERSE_MODE is "demo", only keep the 50 demo tickers.
if UNIVERSE_MODE == "demo":
    CIK_TO_TICKER = {k: v for k, v in _CIK_TO_TICKER_FULL.items() if v in DEMO_TICKERS}

TICKER_TO_CIK = {v: k for k, v in CIK_TO_TICKER.items()}

# Full (unfiltered) ticker-to-CIK mapping — used by the dashboard to let users
# process tickers outside the current UNIVERSE_MODE subset.
FULL_TICKER_TO_CIK = {v: k for k, v in _CIK_TO_TICKER_FULL.items()}

# S&P 500 sector and industry classification (GICS).
TICKER_SECTOR_INDUSTRY = {
    "A": {"sector": "Healthcare", "industry": "Life Sciences Tools & Services"},
    "AAPL": {"sector": "Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    "ABBV": {"sector": "Healthcare", "industry": "Biotechnology"},
    "ABNB": {"sector": "Consumer Cyclical", "industry": "Hotels, Resorts & Cruise Lines"},
    "ABT": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "ACGL": {"sector": "Financial Services", "industry": "Property & Casualty Insurance"},
    "ACN": {"sector": "Technology", "industry": "IT Consulting & Other Services"},
    "ADBE": {"sector": "Technology", "industry": "Application Software"},
    "ADI": {"sector": "Technology", "industry": "Semiconductors"},
    "ADM": {"sector": "Consumer Defensive", "industry": "Agricultural Products & Services"},
    "ADP": {"sector": "Industrials", "industry": "Human Resource & Employment Services"},
    "ADSK": {"sector": "Technology", "industry": "Application Software"},
    "AEE": {"sector": "Utilities", "industry": "Multi-Utilities"},
    "AEP": {"sector": "Utilities", "industry": "Electric Utilities"},
    "AES": {"sector": "Utilities", "industry": "Independent Power Producers & Energy Traders"},
    "AFL": {"sector": "Financial Services", "industry": "Life & Health Insurance"},
    "AIG": {"sector": "Financial Services", "industry": "Multi-line Insurance"},
    "AIZ": {"sector": "Financial Services", "industry": "Multi-line Insurance"},
    "AJG": {"sector": "Financial Services", "industry": "Insurance Brokers"},
    "AKAM": {"sector": "Technology", "industry": "Internet Services & Infrastructure"},
    "ALB": {"sector": "Basic Materials", "industry": "Specialty Chemicals"},
    "ALGN": {"sector": "Healthcare", "industry": "Health Care Supplies"},
    "ALL": {"sector": "Financial Services", "industry": "Property & Casualty Insurance"},
    "ALLE": {"sector": "Industrials", "industry": "Building Products"},
    "AMAT": {"sector": "Technology", "industry": "Semiconductor Materials & Equipment"},
    "AMCR": {"sector": "Basic Materials", "industry": "Paper & Plastic Packaging Products & Materials"},
    "AMD": {"sector": "Technology", "industry": "Semiconductors"},
    "AME": {"sector": "Industrials", "industry": "Electrical Components & Equipment"},
    "AMGN": {"sector": "Healthcare", "industry": "Biotechnology"},
    "AMP": {"sector": "Financial Services", "industry": "Asset Management & Custody Banks"},
    "AMT": {"sector": "Real Estate", "industry": "Telecom Tower REITs"},
    "AMZN": {"sector": "Consumer Cyclical", "industry": "Broadline Retail"},
    "ANET": {"sector": "Technology", "industry": "Communications Equipment"},
    "AON": {"sector": "Financial Services", "industry": "Insurance Brokers"},
    "AOS": {"sector": "Industrials", "industry": "Building Products"},
    "APA": {"sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    "APD": {"sector": "Basic Materials", "industry": "Industrial Gases"},
    "APH": {"sector": "Technology", "industry": "Electronic Components"},
    "APO": {"sector": "Financial Services", "industry": "Asset Management & Custody Banks"},
    "APP": {"sector": "Technology", "industry": "Application Software"},
    "APTV": {"sector": "Consumer Cyclical", "industry": "Automotive Parts & Equipment"},
    "ARE": {"sector": "Real Estate", "industry": "Office REITs"},
    "ARES": {"sector": "Financial Services", "industry": "Asset Management & Custody Banks"},
    "ATO": {"sector": "Utilities", "industry": "Gas Utilities"},
    "AVB": {"sector": "Real Estate", "industry": "Multi-Family Residential REITs"},
    "AVGO": {"sector": "Technology", "industry": "Semiconductors"},
    "AVY": {"sector": "Basic Materials", "industry": "Paper & Plastic Packaging Products & Materials"},
    "AWK": {"sector": "Utilities", "industry": "Water Utilities"},
    "AXON": {"sector": "Industrials", "industry": "Aerospace & Defense"},
    "AXP": {"sector": "Financial Services", "industry": "Consumer Finance"},
    "AZO": {"sector": "Consumer Cyclical", "industry": "Automotive Retail"},
    "BA": {"sector": "Industrials", "industry": "Aerospace & Defense"},
    "BAC": {"sector": "Financial Services", "industry": "Diversified Banks"},
    "BALL": {"sector": "Basic Materials", "industry": "Metal, Glass & Plastic Containers"},
    "BAX": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "BBY": {"sector": "Consumer Cyclical", "industry": "Computer & Electronics Retail"},
    "BDX": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "BEN": {"sector": "Financial Services", "industry": "Asset Management & Custody Banks"},
    "BF.B": {"sector": "Consumer Defensive", "industry": "Distillers & Vintners"},
    "BG": {"sector": "Consumer Defensive", "industry": "Agricultural Products & Services"},
    "BIIB": {"sector": "Healthcare", "industry": "Biotechnology"},
    "BK": {"sector": "Financial Services", "industry": "Asset Management & Custody Banks"},
    "BKNG": {"sector": "Consumer Cyclical", "industry": "Hotels, Resorts & Cruise Lines"},
    "BKR": {"sector": "Energy", "industry": "Oil & Gas Equipment & Services"},
    "BLDR": {"sector": "Industrials", "industry": "Building Products"},
    "BLK": {"sector": "Financial Services", "industry": "Asset Management & Custody Banks"},
    "BMY": {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "BR": {"sector": "Industrials", "industry": "Data Processing & Outsourced Services"},
    "BRK.B": {"sector": "Financial Services", "industry": "Multi-Sector Holdings"},
    "BRO": {"sector": "Financial Services", "industry": "Insurance Brokers"},
    "BSX": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "BX": {"sector": "Financial Services", "industry": "Asset Management & Custody Banks"},
    "BXP": {"sector": "Real Estate", "industry": "Office REITs"},
    "C": {"sector": "Financial Services", "industry": "Diversified Banks"},
    "CAG": {"sector": "Consumer Defensive", "industry": "Packaged Foods & Meats"},
    "CAH": {"sector": "Healthcare", "industry": "Health Care Distributors"},
    "CARR": {"sector": "Industrials", "industry": "Building Products"},
    "CASY": {"sector": "Consumer Defensive", "industry": "Food Retail"},
    "CAT": {"sector": "Industrials", "industry": "Construction Machinery & Heavy Transportation Equipment"},
    "CB": {"sector": "Financial Services", "industry": "Property & Casualty Insurance"},
    "CBOE": {"sector": "Financial Services", "industry": "Financial Exchanges & Data"},
    "CBRE": {"sector": "Real Estate", "industry": "Real Estate Services"},
    "CCI": {"sector": "Real Estate", "industry": "Telecom Tower REITs"},
    "CCL": {"sector": "Consumer Cyclical", "industry": "Hotels, Resorts & Cruise Lines"},
    "CDNS": {"sector": "Technology", "industry": "Application Software"},
    "CDW": {"sector": "Technology", "industry": "Technology Distributors"},
    "CEG": {"sector": "Utilities", "industry": "Electric Utilities"},
    "CF": {"sector": "Basic Materials", "industry": "Fertilizers & Agricultural Chemicals"},
    "CFG": {"sector": "Financial Services", "industry": "Regional Banks"},
    "CHD": {"sector": "Consumer Defensive", "industry": "Household Products"},
    "CHRW": {"sector": "Industrials", "industry": "Air Freight & Logistics"},
    "CHTR": {"sector": "Communication Services", "industry": "Cable & Satellite"},
    "CI": {"sector": "Healthcare", "industry": "Health Care Services"},
    "CIEN": {"sector": "Technology", "industry": "Communications Equipment"},
    "CINF": {"sector": "Financial Services", "industry": "Property & Casualty Insurance"},
    "CL": {"sector": "Consumer Defensive", "industry": "Household Products"},
    "CLX": {"sector": "Consumer Defensive", "industry": "Household Products"},
    "CMCSA": {"sector": "Communication Services", "industry": "Cable & Satellite"},
    "CME": {"sector": "Financial Services", "industry": "Financial Exchanges & Data"},
    "CMG": {"sector": "Consumer Cyclical", "industry": "Restaurants"},
    "CMI": {"sector": "Industrials", "industry": "Construction Machinery & Heavy Transportation Equipment"},
    "CMS": {"sector": "Utilities", "industry": "Multi-Utilities"},
    "CNC": {"sector": "Healthcare", "industry": "Managed Health Care"},
    "CNP": {"sector": "Utilities", "industry": "Multi-Utilities"},
    "COF": {"sector": "Financial Services", "industry": "Consumer Finance"},
    "COHR": {"sector": "Technology", "industry": "Electronic Components"},
    "COIN": {"sector": "Financial Services", "industry": "Financial Exchanges & Data"},
    "COO": {"sector": "Healthcare", "industry": "Health Care Supplies"},
    "COP": {"sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    "COR": {"sector": "Healthcare", "industry": "Health Care Distributors"},
    "COST": {"sector": "Consumer Defensive", "industry": "Consumer Staples Merchandise Retail"},
    "CPAY": {"sector": "Financial Services", "industry": "Transaction & Payment Processing Services"},
    "CPB": {"sector": "Consumer Defensive", "industry": "Packaged Foods & Meats"},
    "CPRT": {"sector": "Industrials", "industry": "Diversified Support Services"},
    "CPT": {"sector": "Real Estate", "industry": "Multi-Family Residential REITs"},
    "CRH": {"sector": "Basic Materials", "industry": "Construction Materials"},
    "CRL": {"sector": "Healthcare", "industry": "Life Sciences Tools & Services"},
    "CRM": {"sector": "Technology", "industry": "Application Software"},
    "CRWD": {"sector": "Technology", "industry": "Systems Software"},
    "CSCO": {"sector": "Technology", "industry": "Communications Equipment"},
    "CSGP": {"sector": "Real Estate", "industry": "Real Estate Services"},
    "CSX": {"sector": "Industrials", "industry": "Rail Transportation"},
    "CTAS": {"sector": "Industrials", "industry": "Diversified Support Services"},
    "CTRA": {"sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    "CTSH": {"sector": "Technology", "industry": "IT Consulting & Other Services"},
    "CTVA": {"sector": "Basic Materials", "industry": "Fertilizers & Agricultural Chemicals"},
    "CVNA": {"sector": "Consumer Cyclical", "industry": "Automotive Retail"},
    "CVS": {"sector": "Healthcare", "industry": "Health Care Services"},
    "CVX": {"sector": "Energy", "industry": "Integrated Oil & Gas"},
    "D": {"sector": "Utilities", "industry": "Multi-Utilities"},
    "DAL": {"sector": "Industrials", "industry": "Passenger Airlines"},
    "DASH": {"sector": "Consumer Cyclical", "industry": "Specialized Consumer Services"},
    "DD": {"sector": "Basic Materials", "industry": "Specialty Chemicals"},
    "DDOG": {"sector": "Technology", "industry": "Application Software"},
    "DE": {"sector": "Industrials", "industry": "Agricultural & Farm Machinery"},
    "DECK": {"sector": "Consumer Cyclical", "industry": "Footwear"},
    "DELL": {"sector": "Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    "DG": {"sector": "Consumer Defensive", "industry": "Consumer Staples Merchandise Retail"},
    "DGX": {"sector": "Healthcare", "industry": "Health Care Services"},
    "DHI": {"sector": "Consumer Cyclical", "industry": "Homebuilding"},
    "DHR": {"sector": "Healthcare", "industry": "Life Sciences Tools & Services"},
    "DIS": {"sector": "Communication Services", "industry": "Movies & Entertainment"},
    "DLR": {"sector": "Real Estate", "industry": "Data Center REITs"},
    "DLTR": {"sector": "Consumer Defensive", "industry": "Consumer Staples Merchandise Retail"},
    "DOC": {"sector": "Real Estate", "industry": "Health Care REITs"},
    "DOV": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "DOW": {"sector": "Basic Materials", "industry": "Commodity Chemicals"},
    "DPZ": {"sector": "Consumer Cyclical", "industry": "Restaurants"},
    "DRI": {"sector": "Consumer Cyclical", "industry": "Restaurants"},
    "DTE": {"sector": "Utilities", "industry": "Multi-Utilities"},
    "DUK": {"sector": "Utilities", "industry": "Electric Utilities"},
    "DVA": {"sector": "Healthcare", "industry": "Health Care Services"},
    "DVN": {"sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    "DXCM": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "EA": {"sector": "Communication Services", "industry": "Interactive Home Entertainment"},
    "EBAY": {"sector": "Consumer Cyclical", "industry": "Broadline Retail"},
    "ECL": {"sector": "Basic Materials", "industry": "Specialty Chemicals"},
    "ED": {"sector": "Utilities", "industry": "Multi-Utilities"},
    "EFX": {"sector": "Industrials", "industry": "Research & Consulting Services"},
    "EG": {"sector": "Financial Services", "industry": "Reinsurance"},
    "EIX": {"sector": "Utilities", "industry": "Electric Utilities"},
    "EL": {"sector": "Consumer Defensive", "industry": "Personal Care Products"},
    "ELV": {"sector": "Healthcare", "industry": "Managed Health Care"},
    "EME": {"sector": "Industrials", "industry": "Construction & Engineering"},
    "EMR": {"sector": "Industrials", "industry": "Electrical Components & Equipment"},
    "EOG": {"sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    "EPAM": {"sector": "Technology", "industry": "IT Consulting & Other Services"},
    "EQIX": {"sector": "Real Estate", "industry": "Data Center REITs"},
    "EQR": {"sector": "Real Estate", "industry": "Multi-Family Residential REITs"},
    "EQT": {"sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    "ERIE": {"sector": "Financial Services", "industry": "Insurance Brokers"},
    "ES": {"sector": "Utilities", "industry": "Electric Utilities"},
    "ESS": {"sector": "Real Estate", "industry": "Multi-Family Residential REITs"},
    "ETN": {"sector": "Industrials", "industry": "Electrical Components & Equipment"},
    "ETR": {"sector": "Utilities", "industry": "Electric Utilities"},
    "EVRG": {"sector": "Utilities", "industry": "Electric Utilities"},
    "EW": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "EXC": {"sector": "Utilities", "industry": "Electric Utilities"},
    "EXE": {"sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    "EXPD": {"sector": "Industrials", "industry": "Air Freight & Logistics"},
    "EXPE": {"sector": "Consumer Cyclical", "industry": "Hotels, Resorts & Cruise Lines"},
    "EXR": {"sector": "Real Estate", "industry": "Self-Storage REITs"},
    "F": {"sector": "Consumer Cyclical", "industry": "Automobile Manufacturers"},
    "FANG": {"sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    "FAST": {"sector": "Industrials", "industry": "Trading Companies & Distributors"},
    "FCX": {"sector": "Basic Materials", "industry": "Copper"},
    "FDS": {"sector": "Financial Services", "industry": "Financial Exchanges & Data"},
    "FDX": {"sector": "Industrials", "industry": "Air Freight & Logistics"},
    "FE": {"sector": "Utilities", "industry": "Electric Utilities"},
    "FFIV": {"sector": "Technology", "industry": "Communications Equipment"},
    "FICO": {"sector": "Technology", "industry": "Application Software"},
    "FIS": {"sector": "Financial Services", "industry": "Transaction & Payment Processing Services"},
    "FISV": {"sector": "Financial Services", "industry": "Transaction & Payment Processing Services"},
    "FITB": {"sector": "Financial Services", "industry": "Regional Banks"},
    "FIX": {"sector": "Industrials", "industry": "Construction & Engineering"},
    "FOX": {"sector": "Communication Services", "industry": "Broadcasting"},
    "FOXA": {"sector": "Communication Services", "industry": "Broadcasting"},
    "FRT": {"sector": "Real Estate", "industry": "Retail REITs"},
    "FSLR": {"sector": "Technology", "industry": "Semiconductors"},
    "FTNT": {"sector": "Technology", "industry": "Systems Software"},
    "FTV": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "GD": {"sector": "Industrials", "industry": "Aerospace & Defense"},
    "GDDY": {"sector": "Technology", "industry": "Internet Services & Infrastructure"},
    "GE": {"sector": "Industrials", "industry": "Aerospace & Defense"},
    "GEHC": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "GEN": {"sector": "Technology", "industry": "Systems Software"},
    "GEV": {"sector": "Industrials", "industry": "Heavy Electrical Equipment"},
    "GILD": {"sector": "Healthcare", "industry": "Biotechnology"},
    "GIS": {"sector": "Consumer Defensive", "industry": "Packaged Foods & Meats"},
    "GL": {"sector": "Financial Services", "industry": "Life & Health Insurance"},
    "GLW": {"sector": "Technology", "industry": "Electronic Components"},
    "GM": {"sector": "Consumer Cyclical", "industry": "Automobile Manufacturers"},
    "GNRC": {"sector": "Industrials", "industry": "Electrical Components & Equipment"},
    "GOOG": {"sector": "Communication Services", "industry": "Interactive Media & Services"},
    "GOOGL": {"sector": "Communication Services", "industry": "Interactive Media & Services"},
    "GPC": {"sector": "Consumer Cyclical", "industry": "Distributors"},
    "GPN": {"sector": "Financial Services", "industry": "Transaction & Payment Processing Services"},
    "GRMN": {"sector": "Consumer Cyclical", "industry": "Consumer Electronics"},
    "GS": {"sector": "Financial Services", "industry": "Investment Banking & Brokerage"},
    "GWW": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "HAL": {"sector": "Energy", "industry": "Oil & Gas Equipment & Services"},
    "HAS": {"sector": "Consumer Cyclical", "industry": "Leisure Products"},
    "HBAN": {"sector": "Financial Services", "industry": "Regional Banks"},
    "HCA": {"sector": "Healthcare", "industry": "Health Care Facilities"},
    "HD": {"sector": "Consumer Cyclical", "industry": "Home Improvement Retail"},
    "HIG": {"sector": "Financial Services", "industry": "Property & Casualty Insurance"},
    "HII": {"sector": "Industrials", "industry": "Aerospace & Defense"},
    "HLT": {"sector": "Consumer Cyclical", "industry": "Hotels, Resorts & Cruise Lines"},
    "HON": {"sector": "Industrials", "industry": "Industrial Conglomerates"},
    "HOOD": {"sector": "Financial Services", "industry": "Investment Banking & Brokerage"},
    "HPE": {"sector": "Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    "HPQ": {"sector": "Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    "HRL": {"sector": "Consumer Defensive", "industry": "Packaged Foods & Meats"},
    "HSIC": {"sector": "Healthcare", "industry": "Health Care Distributors"},
    "HST": {"sector": "Real Estate", "industry": "Hotel & Resort REITs"},
    "HSY": {"sector": "Consumer Defensive", "industry": "Packaged Foods & Meats"},
    "HUBB": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "HUM": {"sector": "Healthcare", "industry": "Managed Health Care"},
    "HWM": {"sector": "Industrials", "industry": "Aerospace & Defense"},
    "IBKR": {"sector": "Financial Services", "industry": "Investment Banking & Brokerage"},
    "IBM": {"sector": "Technology", "industry": "IT Consulting & Other Services"},
    "ICE": {"sector": "Financial Services", "industry": "Financial Exchanges & Data"},
    "IDXX": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "IEX": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "IFF": {"sector": "Basic Materials", "industry": "Specialty Chemicals"},
    "INCY": {"sector": "Healthcare", "industry": "Biotechnology"},
    "INTC": {"sector": "Technology", "industry": "Semiconductors"},
    "INTU": {"sector": "Technology", "industry": "Application Software"},
    "INVH": {"sector": "Real Estate", "industry": "Single-Family Residential REITs"},
    "IP": {"sector": "Basic Materials", "industry": "Paper & Plastic Packaging Products & Materials"},
    "IQV": {"sector": "Healthcare", "industry": "Life Sciences Tools & Services"},
    "IR": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "IRM": {"sector": "Real Estate", "industry": "Other Specialized REITs"},
    "ISRG": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "IT": {"sector": "Technology", "industry": "IT Consulting & Other Services"},
    "ITW": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "IVZ": {"sector": "Financial Services", "industry": "Asset Management & Custody Banks"},
    "J": {"sector": "Industrials", "industry": "Construction & Engineering"},
    "JBHT": {"sector": "Industrials", "industry": "Cargo Ground Transportation"},
    "JBL": {"sector": "Technology", "industry": "Electronic Manufacturing Services"},
    "JCI": {"sector": "Industrials", "industry": "Building Products"},
    "JKHY": {"sector": "Financial Services", "industry": "Transaction & Payment Processing Services"},
    "JNJ": {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "JPM": {"sector": "Financial Services", "industry": "Diversified Banks"},
    "KDP": {"sector": "Consumer Defensive", "industry": "Soft Drinks & Non-alcoholic Beverages"},
    "KEY": {"sector": "Financial Services", "industry": "Regional Banks"},
    "KEYS": {"sector": "Technology", "industry": "Electronic Equipment & Instruments"},
    "KHC": {"sector": "Consumer Defensive", "industry": "Packaged Foods & Meats"},
    "KIM": {"sector": "Real Estate", "industry": "Retail REITs"},
    "KKR": {"sector": "Financial Services", "industry": "Asset Management & Custody Banks"},
    "KLAC": {"sector": "Technology", "industry": "Semiconductor Materials & Equipment"},
    "KMB": {"sector": "Consumer Defensive", "industry": "Household Products"},
    "KMI": {"sector": "Energy", "industry": "Oil & Gas Storage & Transportation"},
    "KO": {"sector": "Consumer Defensive", "industry": "Soft Drinks & Non-alcoholic Beverages"},
    "KR": {"sector": "Consumer Defensive", "industry": "Food Retail"},
    "KVUE": {"sector": "Consumer Defensive", "industry": "Personal Care Products"},
    "L": {"sector": "Financial Services", "industry": "Multi-line Insurance"},
    "LDOS": {"sector": "Industrials", "industry": "Diversified Support Services"},
    "LEN": {"sector": "Consumer Cyclical", "industry": "Homebuilding"},
    "LH": {"sector": "Healthcare", "industry": "Health Care Services"},
    "LHX": {"sector": "Industrials", "industry": "Aerospace & Defense"},
    "LII": {"sector": "Industrials", "industry": "Building Products"},
    "LIN": {"sector": "Basic Materials", "industry": "Industrial Gases"},
    "LITE": {"sector": "Technology", "industry": "Communications Equipment"},
    "LLY": {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "LMT": {"sector": "Industrials", "industry": "Aerospace & Defense"},
    "LNT": {"sector": "Utilities", "industry": "Electric Utilities"},
    "LOW": {"sector": "Consumer Cyclical", "industry": "Home Improvement Retail"},
    "LRCX": {"sector": "Technology", "industry": "Semiconductor Materials & Equipment"},
    "LULU": {"sector": "Consumer Cyclical", "industry": "Apparel, Accessories & Luxury Goods"},
    "LUV": {"sector": "Industrials", "industry": "Passenger Airlines"},
    "LVS": {"sector": "Consumer Cyclical", "industry": "Casinos & Gaming"},
    "LYB": {"sector": "Basic Materials", "industry": "Specialty Chemicals"},
    "LYV": {"sector": "Communication Services", "industry": "Movies & Entertainment"},
    "MA": {"sector": "Financial Services", "industry": "Transaction & Payment Processing Services"},
    "MAA": {"sector": "Real Estate", "industry": "Multi-Family Residential REITs"},
    "MAR": {"sector": "Consumer Cyclical", "industry": "Hotels, Resorts & Cruise Lines"},
    "MAS": {"sector": "Industrials", "industry": "Building Products"},
    "MCD": {"sector": "Consumer Cyclical", "industry": "Restaurants"},
    "MCHP": {"sector": "Technology", "industry": "Semiconductors"},
    "MCK": {"sector": "Healthcare", "industry": "Health Care Distributors"},
    "MCO": {"sector": "Financial Services", "industry": "Financial Exchanges & Data"},
    "MDLZ": {"sector": "Consumer Defensive", "industry": "Packaged Foods & Meats"},
    "MDT": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "MET": {"sector": "Financial Services", "industry": "Life & Health Insurance"},
    "META": {"sector": "Communication Services", "industry": "Interactive Media & Services"},
    "MGM": {"sector": "Consumer Cyclical", "industry": "Casinos & Gaming"},
    "MKC": {"sector": "Consumer Defensive", "industry": "Packaged Foods & Meats"},
    "MLM": {"sector": "Basic Materials", "industry": "Construction Materials"},
    "MMM": {"sector": "Industrials", "industry": "Industrial Conglomerates"},
    "MNST": {"sector": "Consumer Defensive", "industry": "Soft Drinks & Non-alcoholic Beverages"},
    "MO": {"sector": "Consumer Defensive", "industry": "Tobacco"},
    "MOS": {"sector": "Basic Materials", "industry": "Fertilizers & Agricultural Chemicals"},
    "MPC": {"sector": "Energy", "industry": "Oil & Gas Refining & Marketing"},
    "MPWR": {"sector": "Technology", "industry": "Semiconductors"},
    "MRK": {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "MRNA": {"sector": "Healthcare", "industry": "Biotechnology"},
    "MRSH": {"sector": "Financial Services", "industry": "Insurance Brokers"},
    "MS": {"sector": "Financial Services", "industry": "Investment Banking & Brokerage"},
    "MSCI": {"sector": "Financial Services", "industry": "Financial Exchanges & Data"},
    "MSFT": {"sector": "Technology", "industry": "Systems Software"},
    "MSI": {"sector": "Technology", "industry": "Communications Equipment"},
    "MTB": {"sector": "Financial Services", "industry": "Regional Banks"},
    "MTD": {"sector": "Healthcare", "industry": "Life Sciences Tools & Services"},
    "MU": {"sector": "Technology", "industry": "Semiconductors"},
    "NCLH": {"sector": "Consumer Cyclical", "industry": "Hotels, Resorts & Cruise Lines"},
    "NDAQ": {"sector": "Financial Services", "industry": "Financial Exchanges & Data"},
    "NDSN": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "NEE": {"sector": "Utilities", "industry": "Multi-Utilities"},
    "NEM": {"sector": "Basic Materials", "industry": "Gold"},
    "NFLX": {"sector": "Communication Services", "industry": "Movies & Entertainment"},
    "NI": {"sector": "Utilities", "industry": "Multi-Utilities"},
    "NKE": {"sector": "Consumer Cyclical", "industry": "Apparel, Accessories & Luxury Goods"},
    "NOC": {"sector": "Industrials", "industry": "Aerospace & Defense"},
    "NOW": {"sector": "Technology", "industry": "Systems Software"},
    "NRG": {"sector": "Utilities", "industry": "Independent Power Producers & Energy Traders"},
    "NSC": {"sector": "Industrials", "industry": "Rail Transportation"},
    "NTAP": {"sector": "Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    "NTRS": {"sector": "Financial Services", "industry": "Asset Management & Custody Banks"},
    "NUE": {"sector": "Basic Materials", "industry": "Steel"},
    "NVDA": {"sector": "Technology", "industry": "Semiconductors"},
    "NVR": {"sector": "Consumer Cyclical", "industry": "Homebuilding"},
    "NWS": {"sector": "Communication Services", "industry": "Publishing"},
    "NWSA": {"sector": "Communication Services", "industry": "Publishing"},
    "NXPI": {"sector": "Technology", "industry": "Semiconductors"},
    "O": {"sector": "Real Estate", "industry": "Retail REITs"},
    "ODFL": {"sector": "Industrials", "industry": "Cargo Ground Transportation"},
    "OKE": {"sector": "Energy", "industry": "Oil & Gas Storage & Transportation"},
    "OMC": {"sector": "Communication Services", "industry": "Advertising"},
    "ON": {"sector": "Technology", "industry": "Semiconductors"},
    "ORCL": {"sector": "Technology", "industry": "Application Software"},
    "ORLY": {"sector": "Consumer Cyclical", "industry": "Automotive Retail"},
    "OTIS": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "OXY": {"sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    "PANW": {"sector": "Technology", "industry": "Systems Software"},
    "PAYX": {"sector": "Industrials", "industry": "Human Resource & Employment Services"},
    "PCAR": {"sector": "Industrials", "industry": "Construction Machinery & Heavy Transportation Equipment"},
    "PCG": {"sector": "Utilities", "industry": "Multi-Utilities"},
    "PEG": {"sector": "Utilities", "industry": "Electric Utilities"},
    "PEP": {"sector": "Consumer Defensive", "industry": "Soft Drinks & Non-alcoholic Beverages"},
    "PFE": {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "PFG": {"sector": "Financial Services", "industry": "Life & Health Insurance"},
    "PG": {"sector": "Consumer Defensive", "industry": "Personal Care Products"},
    "PGR": {"sector": "Financial Services", "industry": "Property & Casualty Insurance"},
    "PH": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "PHM": {"sector": "Consumer Cyclical", "industry": "Homebuilding"},
    "PKG": {"sector": "Basic Materials", "industry": "Paper & Plastic Packaging Products & Materials"},
    "PLD": {"sector": "Real Estate", "industry": "Industrial REITs"},
    "PLTR": {"sector": "Technology", "industry": "Application Software"},
    "PM": {"sector": "Consumer Defensive", "industry": "Tobacco"},
    "PNC": {"sector": "Financial Services", "industry": "Diversified Banks"},
    "PNR": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "PNW": {"sector": "Utilities", "industry": "Multi-Utilities"},
    "PODD": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "POOL": {"sector": "Consumer Cyclical", "industry": "Distributors"},
    "PPG": {"sector": "Basic Materials", "industry": "Specialty Chemicals"},
    "PPL": {"sector": "Utilities", "industry": "Electric Utilities"},
    "PRU": {"sector": "Financial Services", "industry": "Life & Health Insurance"},
    "PSA": {"sector": "Real Estate", "industry": "Self-Storage REITs"},
    "PSKY": {"sector": "Communication Services", "industry": "Movies & Entertainment"},
    "PSX": {"sector": "Energy", "industry": "Oil & Gas Refining & Marketing"},
    "PTC": {"sector": "Technology", "industry": "Application Software"},
    "PWR": {"sector": "Industrials", "industry": "Construction & Engineering"},
    "PYPL": {"sector": "Financial Services", "industry": "Transaction & Payment Processing Services"},
    "Q": {"sector": "Technology", "industry": "Semiconductor Materials & Equipment"},
    "QCOM": {"sector": "Technology", "industry": "Semiconductors"},
    "RCL": {"sector": "Consumer Cyclical", "industry": "Hotels, Resorts & Cruise Lines"},
    "REG": {"sector": "Real Estate", "industry": "Retail REITs"},
    "REGN": {"sector": "Healthcare", "industry": "Biotechnology"},
    "RF": {"sector": "Financial Services", "industry": "Regional Banks"},
    "RJF": {"sector": "Financial Services", "industry": "Investment Banking & Brokerage"},
    "RL": {"sector": "Consumer Cyclical", "industry": "Apparel, Accessories & Luxury Goods"},
    "RMD": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "ROK": {"sector": "Industrials", "industry": "Electrical Components & Equipment"},
    "ROL": {"sector": "Industrials", "industry": "Environmental & Facilities Services"},
    "ROP": {"sector": "Technology", "industry": "Electronic Equipment & Instruments"},
    "ROST": {"sector": "Consumer Cyclical", "industry": "Apparel Retail"},
    "RSG": {"sector": "Industrials", "industry": "Environmental & Facilities Services"},
    "RTX": {"sector": "Industrials", "industry": "Aerospace & Defense"},
    "RVTY": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "SATS": {"sector": "Communication Services", "industry": "Wireless Telecommunication Services"},
    "SBAC": {"sector": "Real Estate", "industry": "Telecom Tower REITs"},
    "SBUX": {"sector": "Consumer Cyclical", "industry": "Restaurants"},
    "SCHW": {"sector": "Financial Services", "industry": "Investment Banking & Brokerage"},
    "SHW": {"sector": "Basic Materials", "industry": "Specialty Chemicals"},
    "SJM": {"sector": "Consumer Defensive", "industry": "Packaged Foods & Meats"},
    "SLB": {"sector": "Energy", "industry": "Oil & Gas Equipment & Services"},
    "SMCI": {"sector": "Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    "SNA": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "SNDK": {"sector": "Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    "SNPS": {"sector": "Technology", "industry": "Application Software"},
    "SO": {"sector": "Utilities", "industry": "Electric Utilities"},
    "SOLV": {"sector": "Healthcare", "industry": "Health Care Technology"},
    "SPG": {"sector": "Real Estate", "industry": "Retail REITs"},
    "SPGI": {"sector": "Financial Services", "industry": "Financial Exchanges & Data"},
    "SRE": {"sector": "Utilities", "industry": "Multi-Utilities"},
    "STE": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "STLD": {"sector": "Basic Materials", "industry": "Steel"},
    "STT": {"sector": "Financial Services", "industry": "Asset Management & Custody Banks"},
    "STX": {"sector": "Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    "STZ": {"sector": "Consumer Defensive", "industry": "Distillers & Vintners"},
    "SW": {"sector": "Basic Materials", "industry": "Paper & Plastic Packaging Products & Materials"},
    "SWK": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "SWKS": {"sector": "Technology", "industry": "Semiconductors"},
    "SYF": {"sector": "Financial Services", "industry": "Consumer Finance"},
    "SYK": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "SYY": {"sector": "Consumer Defensive", "industry": "Food Distributors"},
    "T": {"sector": "Communication Services", "industry": "Integrated Telecommunication Services"},
    "TAP": {"sector": "Consumer Defensive", "industry": "Brewers"},
    "TDG": {"sector": "Industrials", "industry": "Aerospace & Defense"},
    "TDY": {"sector": "Technology", "industry": "Electronic Equipment & Instruments"},
    "TECH": {"sector": "Healthcare", "industry": "Life Sciences Tools & Services"},
    "TEL": {"sector": "Technology", "industry": "Electronic Manufacturing Services"},
    "TER": {"sector": "Technology", "industry": "Semiconductor Materials & Equipment"},
    "TFC": {"sector": "Financial Services", "industry": "Diversified Banks"},
    "TGT": {"sector": "Consumer Defensive", "industry": "Consumer Staples Merchandise Retail"},
    "TJX": {"sector": "Consumer Cyclical", "industry": "Apparel Retail"},
    "TKO": {"sector": "Communication Services", "industry": "Movies & Entertainment"},
    "TMO": {"sector": "Healthcare", "industry": "Life Sciences Tools & Services"},
    "TMUS": {"sector": "Communication Services", "industry": "Wireless Telecommunication Services"},
    "TPL": {"sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    "TPR": {"sector": "Consumer Cyclical", "industry": "Apparel, Accessories & Luxury Goods"},
    "TRGP": {"sector": "Energy", "industry": "Oil & Gas Storage & Transportation"},
    "TRMB": {"sector": "Technology", "industry": "Electronic Equipment & Instruments"},
    "TROW": {"sector": "Financial Services", "industry": "Asset Management & Custody Banks"},
    "TRV": {"sector": "Financial Services", "industry": "Property & Casualty Insurance"},
    "TSCO": {"sector": "Consumer Cyclical", "industry": "Other Specialty Retail"},
    "TSLA": {"sector": "Consumer Cyclical", "industry": "Automobile Manufacturers"},
    "TSN": {"sector": "Consumer Defensive", "industry": "Packaged Foods & Meats"},
    "TT": {"sector": "Industrials", "industry": "Building Products"},
    "TTD": {"sector": "Communication Services", "industry": "Advertising"},
    "TTWO": {"sector": "Communication Services", "industry": "Interactive Home Entertainment"},
    "TXN": {"sector": "Technology", "industry": "Semiconductors"},
    "TXT": {"sector": "Industrials", "industry": "Aerospace & Defense"},
    "TYL": {"sector": "Technology", "industry": "Application Software"},
    "UAL": {"sector": "Industrials", "industry": "Passenger Airlines"},
    "UBER": {"sector": "Industrials", "industry": "Passenger Ground Transportation"},
    "UDR": {"sector": "Real Estate", "industry": "Multi-Family Residential REITs"},
    "UHS": {"sector": "Healthcare", "industry": "Health Care Facilities"},
    "ULTA": {"sector": "Consumer Cyclical", "industry": "Other Specialty Retail"},
    "UNH": {"sector": "Healthcare", "industry": "Managed Health Care"},
    "UNP": {"sector": "Industrials", "industry": "Rail Transportation"},
    "UPS": {"sector": "Industrials", "industry": "Air Freight & Logistics"},
    "URI": {"sector": "Industrials", "industry": "Trading Companies & Distributors"},
    "USB": {"sector": "Financial Services", "industry": "Diversified Banks"},
    "V": {"sector": "Financial Services", "industry": "Transaction & Payment Processing Services"},
    "VICI": {"sector": "Real Estate", "industry": "Hotel & Resort REITs"},
    "VLO": {"sector": "Energy", "industry": "Oil & Gas Refining & Marketing"},
    "VLTO": {"sector": "Industrials", "industry": "Environmental & Facilities Services"},
    "VMC": {"sector": "Basic Materials", "industry": "Construction Materials"},
    "VRSK": {"sector": "Industrials", "industry": "Research & Consulting Services"},
    "VRSN": {"sector": "Technology", "industry": "Internet Services & Infrastructure"},
    "VRT": {"sector": "Industrials", "industry": "Electrical Components & Equipment"},
    "VRTX": {"sector": "Healthcare", "industry": "Biotechnology"},
    "VST": {"sector": "Utilities", "industry": "Electric Utilities"},
    "VTR": {"sector": "Real Estate", "industry": "Health Care REITs"},
    "VTRS": {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "VZ": {"sector": "Communication Services", "industry": "Integrated Telecommunication Services"},
    "WAB": {"sector": "Industrials", "industry": "Construction Machinery & Heavy Transportation Equipment"},
    "WAT": {"sector": "Healthcare", "industry": "Life Sciences Tools & Services"},
    "WBD": {"sector": "Communication Services", "industry": "Broadcasting"},
    "WDAY": {"sector": "Technology", "industry": "Application Software"},
    "WDC": {"sector": "Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    "WEC": {"sector": "Utilities", "industry": "Electric Utilities"},
    "WELL": {"sector": "Real Estate", "industry": "Health Care REITs"},
    "WFC": {"sector": "Financial Services", "industry": "Diversified Banks"},
    "WM": {"sector": "Industrials", "industry": "Environmental & Facilities Services"},
    "WMB": {"sector": "Energy", "industry": "Oil & Gas Storage & Transportation"},
    "WMT": {"sector": "Consumer Defensive", "industry": "Consumer Staples Merchandise Retail"},
    "WRB": {"sector": "Financial Services", "industry": "Property & Casualty Insurance"},
    "WSM": {"sector": "Consumer Cyclical", "industry": "Homefurnishing Retail"},
    "WST": {"sector": "Healthcare", "industry": "Health Care Supplies"},
    "WTW": {"sector": "Financial Services", "industry": "Insurance Brokers"},
    "WY": {"sector": "Real Estate", "industry": "Timber REITs"},
    "WYNN": {"sector": "Consumer Cyclical", "industry": "Casinos & Gaming"},
    "XEL": {"sector": "Utilities", "industry": "Multi-Utilities"},
    "XOM": {"sector": "Energy", "industry": "Integrated Oil & Gas"},
    "XYL": {"sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    "XYZ": {"sector": "Financial Services", "industry": "Transaction & Payment Processing Services"},
    "YUM": {"sector": "Consumer Cyclical", "industry": "Restaurants"},
    "ZBH": {"sector": "Healthcare", "industry": "Health Care Equipment"},
    "ZBRA": {"sector": "Technology", "industry": "Electronic Equipment & Instruments"},
    "ZTS": {"sector": "Healthcare", "industry": "Pharmaceuticals"},
}

ITEM_SECTIONS = [
    "item_1",
    "item_1a",
    "item_1b",
    "item_1c",
    "item_2",
    "item_3",
    "item_4",
    "item_5",
    "item_6",
    "item_7",
    "item_7a",
    "item_8",
    "item_9",
    "item_9a",
    "item_9b",
    "item_10",
    "item_11",
    "item_12",
    "item_13",
    "item_14",
    "item_15",
]

# Per-section importance weights for the weighted change_intensity calculation.
# Inspired by the LazyPrices paper: MD&A, Risk Factors, and Business are the
# strongest predictors of post-filing drift.  Sections absent from this dict
# are ignored (weight 0).  The weighted average divides by the sum of weights
# for sections actually present, so missing sections don't penalise the score.
SECTION_WEIGHTS = {
    "item_1":  0.15,   # Business
    "item_1a": 0.25,   # Risk Factors
    "item_1b": 0.02,   # Unresolved Staff Comments
    "item_1c": 0.02,   # Cybersecurity
    "item_2":  0.02,   # Properties
    "item_3":  0.01,   # Legal Proceedings
    "item_4":  0.01,   # Mine Safety Disclosures
    "item_5":  0.02,   # Market for Common Equity
    "item_6":  0.01,   # Reserved
    "item_7":  0.30,   # MD&A (strongest predictor)
    "item_7a": 0.10,   # Quantitative & Qualitative Market Risk
    "item_8":  0.05,   # Financial Statements
    "item_9":  0.01,   # Accountant Changes / Disagreements
    "item_9a": 0.02,   # Controls and Procedures
    "item_9b": 0.01,   # Other Information
    "item_10": 0.01,   # Directors / Corporate Governance
    "item_11": 0.01,   # Executive Compensation
    "item_12": 0.01,   # Security Ownership
    "item_13": 0.01,   # Related Transactions
    "item_14": 0.01,   # Principal Accountant Fees
    "item_15": 0.01,   # Exhibits / Financial Statement Schedules
}

# 10-Q sections (Part I and Part II items).  The regex in extract_clean.py
# already matches these patterns; this list is used for section-level LAS.
ITEM_SECTIONS_10Q = [
    "item_1",   # Financial Statements
    "item_2",   # MD&A
    "item_3",   # Quantitative & Qualitative Market Risk
    "item_4",   # Controls and Procedures
    "item_1a",  # Risk Factors (Part II)
    "item_2",   # Unregistered Sales of Equity
    "item_5",   # Other Information
    "item_6",   # Exhibits
]

# Section weights for 10-Q filings (same key sections, fewer sections total).
SECTION_WEIGHTS_10Q = {
    "item_1":  0.10,   # Financial Statements
    "item_2":  0.35,   # MD&A (strongest predictor, same as 10-K item_7)
    "item_3":  0.15,   # Quantitative & Qualitative Market Risk
    "item_4":  0.05,   # Controls and Procedures
    "item_1a": 0.30,   # Risk Factors
    "item_5":  0.03,   # Other Information
    "item_6":  0.02,   # Exhibits
}

# Pairing gap (calendar days) for filing type.
# 10-K: annual, gap between 200 and 550 days.
# 10-Q: quarterly, gap between 60 and 150 days.
PAIRING_DAY_RANGE = {
    "10-K": (200, 550),
    "10-Q": (60, 150),
}

PIPELINE_WORKERS = 4  # concurrent CIK workers for run_pipeline.py (--workers flag)

SIMILARITY_MEASURES = ["cosine", "jaccard"]  # supported: cosine, jaccard

NUMERIC_TABLE_THRESHOLD = 0.15

# Weight of text-based similarity in the hybrid change_intensity formula.
# change_intensity = alpha * text_change + (1 - alpha) * numerical_divergence
NUMERIC_CHANGE_ALPHA = 0.7


# CAR (Cumulative Abnormal Return) event window

CAR_WINDOW = (-1, 5)  # trading days relative to filed_date
MARKET_TICKER = "^GSPC"  # S&P 500 as market proxy
CAR_BUFFER_DAYS = 30  # calendar-day buffer when fetching price data

VOLUME_BASELINE_DAYS = 60  # trailing trading days for baseline average volume
VOLUME_BASELINE_GAP = 5    # trading-day gap before event window to avoid leakage

# Composite attention proxy weights (volume ratio + filing delay).
# Filing delay = calendar days from report_date to filed_date.
# Late filers signal lower attention / quality.
ATTENTION_COMPOSITE_WEIGHTS = {
    "volume_ratio": 0.7,
    "filing_delay": 0.3,
}

# 
# LAS formula  –  LAS = w_change * f(change) - w_attention * f(attn) - w_car * f(car)

LAS_WEIGHTS = {
    "w_change": 0.60,
    "w_attention": 0.30,
    "w_car": 0.10,
}

# "rank" (cross-sectional rank percentile) or "zscore"
LAS_NORMALIZATION = "rank"


# Pipeline versioning — bump to force reprocessing of all filings

PIPELINE_VERSION = "1.5"


# LLM settings (advisor narrative)

LLM_MODEL = "gpt-4.1-mini"


# RAG settings
# Toggle RAG_ENABLED to False to revert to plain context-injection chat.
# To switch to AWS, change the provider/store values:
#   RAG_EMBEDDING_PROVIDER = "bedrock"
#   RAG_LLM_PROVIDER = "bedrock"
#   RAG_VECTOR_STORE = "opensearch"

# Signal thresholds for buy/sell/hold classification based on LAS components.
# Uses norm_change (rank percentile 0-1), raw attention_proxy, and raw CAR.
SIGNAL_THRESHOLDS = {
    "change_high": 0.70,           # rank percentile cutoff for "high" change
    "change_low": 0.30,            # rank percentile cutoff for "low" change
    "attention_low": 1.0,          # volume ratio below this = inattention
    "car_negative": -0.005,        # CAR below this = negative reaction
    "car_deep_negative": -0.015,   # deep selloff threshold for contrarian buy
}

# Confidence = |change_z| + |attention_z| + |CAR_z|; controls signal strength.
SIGNAL_CONFIDENCE = {
    "strong": 3.0,            # sum of |z| above this = strong recommendation
    "moderate": 1.5,          # between moderate and strong = standard recommendation
}

# High-importance sections that strengthen SELL/CAUTION when they drive the change.
SIGNAL_KEY_SECTIONS = {"item_1a", "item_7", "item_7a"}

# When both item_1a (Risk Factors) and item_7 (MD&A) exceed this threshold,
# the sell signal's change_high requirement is lowered by 0.10 (section boost).
SECTION_SELL_BOOST_THRESHOLD = 0.05


RAG_ENABLED = True
RAG_EMBEDDING_PROVIDER = "openai"           # "openai" | "bedrock"
RAG_EMBEDDING_MODEL = "text-embedding-3-small"
RAG_LLM_PROVIDER = "openai"                # "openai" | "bedrock"
RAG_VECTOR_STORE = "chroma"                 # "chroma" | "opensearch"
RAG_VECTORDB_DIR = os.path.join(DATA_DIR, "vectordb")
RAG_CHUNK_MAX_CHARS = 3000
RAG_CHUNK_OVERLAP = 200
RAG_TOP_K = 5
